### ISSUE TITLE
旧版caffe2无法编译通过？请教～（用新版Caffe2去掉模板声明后仍报错，方便的话请更新适配到新版Caffe2供参考，谢！）

### ISSUE THREAD

**Issue by 666DZY666** [dongfangduoshou123/DaSiamRPN-Caffe2#10]
您提供的旧版Caffe2编译错误，之前还缺了一些头文件，是从新版Caffe2里拷过来的～

caffe2/core/allocator.h:24:20: error: expected constructor, destructor, or type conversion before ‘(’ token CAFFE2_DECLARE_bool(caffe2_report_cpu_memory_usage);

caffe2/core/allocator.h:72:9: error:‘FLAGS_caffe2_cpu_allocator_do_zero_fill’ was not declared in this scope if (FLAGS_caffe2_cpu_allocator_do_zero_fill) {

caffe2/core/allocator.h:73:29: error: ‘memset’ was not declared in this scope memset(data, 0, nbytes);

**Comment by dongfangduoshou123** [comment]
https://github.com/dongfangduoshou123/DaSiamRPN-Caffe2/issues/7

里面有我所用的就caffe2下载链接。
有时间更一下，主要是项目里用的旧的，一直没更。
