### ISSUE TITLE
您好可以请教一下嘛这个我运行不起来 您是怎么编译的？

### ISSUE THREAD

**Issue by l1uw3n** [dongfangduoshou123/DaSiamRPN-Caffe2#2]

**Comment by l1uw3n** [comment]
我尝试安装您给出的caffe2_old发现无法安装，我尝试安装新版本的caffe2可以以安装，但是我感觉您构建的项目是用的qt构建的里面好多caffe2的动态库我并没有编译出来，这个是您复现的嘛？

**Comment by jufeng123** [comment]
我也发现这个问题，caffe2_old编译不过，新版的caffe2里面好像删掉了旧版的部分内容，有无法解析的内容

**Comment by dongfangduoshou123** [comment]
由于caffe2官方旧版地址现在没有内容了，那个caffe2_old我没用过， 我想他是fork的官网的，应该没问题呢。。。。这就比较尴尬了。是我的复现，不过只是inference, 我复现是在就caffe2上做的，没问题。你们使用的时候报的错误是什么，贴出来看看。

**Comment by dongfangduoshou123** [comment]
unix:!macx: LIBS += -L$$PWD/../../../../usr/local/lib/ -lcaffe2_yolo_ops_gpu这个是不需要的，这个是复现yolov3的插件so。。。别的应该没问题的。。。

**Comment by jufeng123** [comment]
是的，旧版caffe2已经都变成只读的了

**Comment by jufeng123** [comment]
能不能具体说一下，使用新版的caffe2会出现什么问题？

**Comment by jufeng123** [comment]
他的caffe2好像现在移到https://github.com/pytorch/pytorch/了，这里面有没有能和你版本匹配的？

**Comment by dongfangduoshou123** [comment]
主要问题是并到pytroch的caffe2他的tensor类实现有了重大改变，旧版caffe2的tensor是模板类，新版caffe2将tensor的模板去掉了，要适配新版caffe2,需要该我实现中所有有关tensor的地方----》修改方式就是去掉其中的模板声明。
yolov3的复现我已經更新至适配新caffe2了，见这个issue的描述：https://github.com/dongfangduoshou123/Caffe2-yolo-v3/issues/2   ;DasiamRPN没做这个工作。

**Comment by jufeng123** [comment]
好的，感谢您的回答！

**Comment by jufeng123** [comment]
您之后有适配新版caffe2的计划吗？

**Comment by l1uw3n** [comment]
谢谢您的回答 ！
