### ISSUE TITLE
gflags和glog问题

### ISSUE THREAD

**Issue by jufeng123** [dongfangduoshou123/DaSiamRPN-Caffe2#8]
感谢您上次分享的caffe2代码，用您的caffe2编译后，错误少了很多，现在还想请问您两个问题：
1：想问一下您使用的gflags和glog的版本，感觉像是我使用的这两个库版本太新了，部分函数存在不兼容的情况。
2：caffe2编译到97%，出现undefined reference to symbol '_ZN2cv6String10deallocateEv'，/usr/local/lib/libopencv_core.so.3.3: error adding symbols: DSO missing from command line，好像是说缺少opencv动态库，但我的opencv3.3.1已经正确安装，在cmake过程中也正确识别，不知道是什么原因。

**Comment by dongfangduoshou123** [comment]
重装一个干净的系统吧

**Comment by jufeng123** [comment]
那我再看看吧

**Comment by jufeng123** [comment]
您好，我重新安装了系统，目前caffe2已经正确编译通过了，相关的caffe2的.so也已经加入到IDE当中，可是仍然提示caffe2中的未定义的引用。
/usr/local/cuda-9.0/bin/nvcc --cudart static -L/home/hx/pytorch/build/lib -L/usr/lib/nvidia-384 -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib --relocatable-device-code=false -gencode arch=compute_61,code=compute_61 -gencode arch=compute_61,code=sm_61 -link -o  "DaSiamRpn"  ./dasiamrpntracker.o ./main.o   -lGL -lxml2 -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_videoio -lpthread -lcublas -lcudart -lcudnn -lcufft -lcurand -lcuda -lcaffe2_gpu -lcaffe2 -lcaffe2_detectron_ops_gpu -lcaffe2_observers -lcaffe2_module_test_dynamic -ldl -lgflags -lglog -lprotobuf -lprotobuf-lite
./dasiamrpntracker.o：在函数‘caffe2::CPUContext::New(unsigned long)’中：
/home/hx/pytorch/caffe2/core/context.h:104：对‘caffe2::FLAGS_caffe2_report_cpu_memory_usage’未定义的引用
./dasiamrpntracker.o：在函数‘caffe2::CUDAContext::~CUDAContext()’中：
/home/hx/pytorch/caffe2/core/context_gpu.h:130：对‘caffe2::MessageLogger::MessageLogger(char const*, int, int)’未定义的引用
/home/hx/pytorch/caffe2/core/context_gpu.h:130：对‘caffe2::MessageLogger::~MessageLogger()’未定义的引用
./dasiamrpntracker.o：在函数‘caffe2::Workspace::~Workspace()’中：
makefile:58: recipe for target 'DaSiamRpn' failed
/home/hx/pytorch/caffe2/core/workspace.h:104：对‘caffe2::FLAGS_caffe2_print_blob_sizes_at_exit’未定义的引用
./dasiamrpntracker.o：在函数‘void caffe2::Tensor<caffe2::CPUContext>::Resize<std::vector<long, std::allocator<long> > >(std::vector<long, std::allocator<long> >)’中：
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_keep_on_shrink’未定义的引用
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_max_keep_on_shrink_memory’未定义的引用
./dasiamrpntracker.o：在函数‘caffe2::Tensor<caffe2::CUDAContext>* caffe2::Blob::GetMutable<caffe2::Tensor<caffe2::CUDAContext> >(bool*)’中：
/home/hx/pytorch/caffe2/core/blob.h:107：对‘caffe2::MessageLogger::MessageLogger(char const*, int, int)’未定义的引用
/home/hx/pytorch/caffe2/core/blob.h:107：对‘caffe2::MessageLogger::~MessageLogger()’未定义的引用
/home/hx/pytorch/caffe2/core/blob.h:107：对‘caffe2::MessageLogger::~MessageLogger()’未定义的引用
./dasiamrpntracker.o：在函数‘void caffe2::Tensor<caffe2::CUDAContext>::Resize<int, int, int, int>(int, int, int, int)’中：
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_keep_on_shrink’未定义的引用
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_max_keep_on_shrink_memory’未定义的引用
./dasiamrpntracker.o：在函数‘caffe2::Tensor<caffe2::CPUContext>* caffe2::Blob::GetMutable<caffe2::Tensor<caffe2::CPUContext> >(bool*)’中：
/home/hx/pytorch/caffe2/core/blob.h:107：对‘caffe2::MessageLogger::MessageLogger(char const*, int, int)’未定义的引用
/home/hx/pytorch/caffe2/core/blob.h:107：对‘caffe2::MessageLogger::~MessageLogger()’未定义的引用
/home/hx/pytorch/caffe2/core/blob.h:107：对‘caffe2::MessageLogger::~MessageLogger()’未定义的引用
./dasiamrpntracker.o：在函数‘void caffe2::Tensor<caffe2::CPUContext>::Resize<int, int, int, int>(int, int, int, int)’中：
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_keep_on_shrink’未定义的引用
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_max_keep_on_shrink_memory’未定义的引用
./dasiamrpntracker.o：在函数‘void caffe2::Tensor<caffe2::CUDAContext>::Resize<std::vector<long, std::allocator<long> > >(std::vector<long, std::allocator<long> >)’中：
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_keep_on_shrink’未定义的引用
/home/hx/pytorch/caffe2/core/tensor.h:300：对‘caffe2::FLAGS_caffe2_max_keep_on_shrink_memory’未定义的引用

您还有什么建议吗？

**Comment by dongfangduoshou123** [comment]
我对你用的这个ide不太熟悉，未定义的引用意思就是对应的so没有引入进来。另外我看你用的是nvcc编译器，我用的是gcc编译器。

**Comment by jufeng123** [comment]
谢谢您的回答，我再研究研究

**Comment by C-peng** [comment]
Did you solve the problem? I met it, too.

**Comment by jufeng123** [comment]
我的问题还没有解决，你的问题具体是什么

**Comment by C-peng** [comment]
/home//pytorch/caffe2/core/context_gpu.h:130: error: undefined reference to `caffe2::MessageLogger::MessageLogger(char const*, int, int)'

**Comment by jufeng123** [comment]
这个问题我也没解决

**Comment by C-peng** [comment]
Did you have the C++ code?

**Comment by dongfangduoshou123** [comment]
> Did you have the C++ code?

Recommond you use Qt as your ide.

**Comment by jufeng123** [comment]
你只有这一个报错还是有很多？

**Comment by jufeng123** [comment]
问一下你用的什么IDE？

**Comment by C-peng** [comment]
My IDE is QT.
