### ISSUE TITLE
Converted model for SiamRPN Baidu

### ISSUE THREAD

**Issue by rozy11a** [dongfangduoshou123/DaSiamRPN-Caffe2#9]
Hi, first of all, thank you for your contribution. Unfortunately I can't download the Converted model for SiamRPN from Baidu as I am not China resident. Can you upload the file to other cloud service that I can download without an account? Thanks.

**Comment by dongfangduoshou123** [comment]
You can also to convert model from original pytorch model yourself use the scirpt  transferToCaffe2.py
